import React from 'react';
import { SEO } from '../components/common/SEO';
import { Breadcrumbs } from '../components/common/Breadcrumbs';

export const TermsPage: React.FC<{ navigate: (route: string) => void }> = ({ navigate }) => {
  return (
    <div className="min-h-screen py-8">
      <SEO
        config={{
          title: 'Terms of Service — Chromora',
          description: 'Terms of service and usage conditions for the Chromora color intelligence suite.',
          canonicalUrl: 'https://chromora.app/terms',
        }}
      />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <Breadcrumbs
          items={[{ name: 'Terms of Service', url: '/terms', isCurrent: true }]}
          onNavigate={navigate}
        />

        <div className="my-8 space-y-3">
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-50">
            Terms of Service
          </h1>
          <p className="text-xs text-zinc-400">Effective Date: January 2026</p>
        </div>

        <div className="space-y-6 text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed py-6 border-t border-zinc-200 dark:border-zinc-800">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using the Chromora web application, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our tools.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
              2. Intellectual Property of Generated Palettes
            </h2>
            <p>
              All color palettes, design tokens, Tailwind code snippets, CSS rules, and exports generated by you using Chromora are 100% royalty-free and belong entirely to you for personal and commercial applications.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
              3. Disclaimer of Warranty
            </h2>
            <p>
              Chromora tools are provided on an "as is" and "as available" basis. While we strive for mathematical accuracy against standard CIE color spaces and WCAG 2.1 formulas, differences in display hardware and color profiles may yield subtle perceptual variations.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};
